site: us
database: retail_starter_pack
run_type: update

tables:
  templates: retail_starter_pack_template
  parent_segment_creation: automation_parent_segments
  active_audience: active_audience
  # folder_logs: folder_logs
  segment_logs: segment_logs  