create:
  level_1:
  - name: 1. Standard Segments
    folderPath:
  - name: 2. Custom Segments
    folderPath:
  - name: 3. Exploratory/ Analytics Segments
    folderPath:
  - name: 4. Testing/ Training
    folderPath:
  level_2:
   - name: Ecomm
     folderPath: ROOT/1. Standard Segments
   - name: Engagement
     folderPath: ROOT/1. Standard Segments
   - name: Genre
     folderPath: ROOT/1. Standard Segments
   - name: Group
     folderPath: ROOT/1. Standard Segments
   - name: Optimization
     folderPath: ROOT/1. Standard Segments
   - name: Campaigns
     folderPath: ROOT/1. Standard Segments
   - name: Re-engagement
     folderPath: ROOT/1. Standard Segments
   - name: Subscription
     folderPath: ROOT/1. Standard Segments
   - name: DSP
     folderPath: ROOT/1. Standard Segments
   - name: Exploratory
     folderPath: ROOT/4. Testing/ Training
  

#leave it as default
include:
  level_0:
  - name: ROOT
    folderPath: