type: segment-batch
id: null
relationships:
  parentFolder:
    data:
      id: ${rootfolder_id}
      type: folder-segment
attributes:
  - audienceId: ${audience_id}
    countPopulation: true
    name: Marktable Users
    rule:
      type: And
      conditions:
      - conditions:
        - type: Value
          leftValue:
            aggregation:
              type: Count
            source:
              name: behavior_enriched_consents
            filter:
              type: And
              conditions:
              - type: Column
                column: consent_flag
                operator:
                  not: false
                  rightValue: 1
                  type: Equal
          operator:
            not: false
            rightValue: 1
            type: GreaterEqual
          exclude: false
        type: And
        description: Users who have given consent
    description: 'Marktable Users - Users who have given consent'
    segmentInsightDashboardId:
