schema_change:
  - raw_table_name: consents
    src_table_name: consents
    columns:
      - src: id
        raw: id
        type: varchar
      - src: id_type
        raw: id_type
        type: varchar
      - src: consent_type
        raw: consent_type
        type: varchar
      - src: consent_flag
        raw: consent_flag
        type: varchar
      - src: time
        raw: time
        type: bigint
  - raw_table_name: 'not exists'
    src_table_name: email_activity
    columns:
      - src: activity_date
        raw: activity_date
        type: varchar
      - src: campaign_id
        raw: campaign_id
        type: varchar
      - src: campaign_name
        raw: campaign_name
        type: varchar
      - src: email
        raw: email
        type: varchar
      - src: customer_id
        raw: customer_id
        type: varchar
      - src: activity_type
        raw: activity_type
        type: varchar
      - src: time
        raw: time
        type: bigint
  - raw_table_name: 'not exists'
    src_table_name: formfills
    columns:
      - src: email
        raw: email
        type: varchar
      - src: phone_number
        raw: phone_number
        type: varchar
      - src: td_global_id
        raw: td_global_id
        type: varchar
      - src: td_client_id
        raw: td_client_id
        type: varchar
      - src: form_type
        raw: form_type
        type: varchar
      - src: time
        raw: time
        type: bigint   
  - raw_table_name: loyalty_profile
    src_table_name: loyalty_profile
    columns:
      - src: customer_id
        raw: crmid
        type: varchar
      - src: email
        raw: emailaddress
        type: varchar
      - src: secondary_email
        raw: null
        type: varchar
      - src: phone_number
        raw: phonenumber
        type: varchar
      - src: first_name
        raw: firstname
        type: varchar
      - src: last_name
        raw: lastname
        type: varchar
      - src: address
        raw: null
        type: varchar
      - src: country
        raw: null
        type: varchar
      - src: city
        raw: null
        type:  varchar
      - src: state
        raw: null
        type: varchar
      - src: postal_code
        raw: null
        type: varchar
      - src: gender
        raw: null
        type: varchar
      - src: date_of_birth
        raw: birthdate
        type: varchar
      - src: membership_status
        raw: null
        type: varchar
      - src: membership_tier
        raw: null
        type: varchar
      - src: net_redeemable_balance
        raw: null
        type: double
      - src: net_debits
        raw: null
        type: double
      - src: membership_points_earned
        raw: null
        type: bigint
      - src: membership_points_balance
        raw: null
        type: bigint
      - src: membership_points_pending
        raw: null
        type: bigint
      - src: total_loyalty_purchases
        raw: null
        type: bigint
      - src: current_membership_level_expiration
        raw: null
        type: varchar
      - src: location_id
        raw: null
        type: varchar
      - src: location_address
        raw: null
        type: varchar
      - src: location_city
        raw: null
        type: varchar
      - src: created_at
        raw: null
        type: varchar
      - src: updated_at
        raw: null
        type: varchar
      - src: time
        raw: time
        type: bigint
  - raw_table_name: order_details
    src_table_name: order_details
    columns:
      - src: order_no
        raw: transactionid
        type: varchar
      - src: order_transaction_type
        raw: paytypename
        type: varchar
      - src: quantity
        raw: quantity 
        type: bigint
      - src: product_id
        raw: sku
        type: varchar
      - src: product_name
        raw: itemdescription
        type: varchar
      - src: product_size
        raw: null
        type: varchar
      - src: product_description
        raw: itemdescription
        type: varchar
      - src: product_department
        raw: storeproductdepartmentname
        type: varchar
      - src: product_sub_department
        raw: storeproductsubdepartmentname
        type: varchar
      - src: list_price
        raw: null
        type: double
      - src: discount_offered
        raw: null
        type: double
      - src: tax
        raw: null
        type: double
      - src: net_price
        raw: amount
        type: double
      - src: order_line_no
        raw: lineitemid
        type: bigint
      - src: time
        raw: time
        type: bigint
