site: us
raw: raw
src: src
stg: stg
sub: retail2
gld: gld
ana: analytics
run_all: true

# US
td_cdp_endpoint: "https://api-cdp.treasuredata.com"
# APAC
# td_cdp_endpoint: "https://api-cdp.ap02.treasuredata.com"
# EMEA
# td_cdp_endpoint: "https://api-cdp.eu01.treasuredata.com"

segment:
  run_type: update
  tables:
    parent_segment_templates: parent_segment_template
    segment_templates: segment_templates
    parent_segment_creation: automation_parent_segments
    active_audience: active_audience
    segment_logs: segment_logs

analytics:
  dashboards:
    sankey:
      register:
        pattern: 'register'
        stage: 'Account Creation/Sign-Up'
        indexno: 0
      login:
        pattern: 'login'
        stage: 'Sign-In/Login'
        indexno: 1
      products:
        pattern: 'products'
        stage: 'Product Page Visit'
        indexno: 2
      wishlist:
        pattern: 'wishlist'
        stage: 'Wishlist/Favorites'
        indexno: 3
      cart:
        pattern: 'cart'
        stage: 'Add to Cart'
        indexno: 4
      checkout:
        pattern: 'checkout'
        stage: 'Checkout Initiation'
        indexno: 5
      loyalty:
        pattern: 'loyalty'
        stage: 'Loyalty Program Enrollment'
        indexno: 6
      return:
        pattern: 'return'
        stage: 'Returns/Exchanges'
        indexno: 7
      review:
        pattern: 'review'
        stage: 'Write a Review'
        indexno: 8
      support:
        pattern: 'support'
        stage: 'Customer Support Ticket'
        indexno: 9