drop table if exists pre_preferred_season;

create table if not exists pre_preferred_season as
with enriched_order_offline_transactions_enriched_order_online_transactions_cte_attributor as (select
trfmd_season as season,
retail_unification_id as retail_unification_id,
order_no as order_no
 from enriched_order_online_transactions
 union all
select
trfmd_season as season,
retail_unification_id as retail_unification_id,
order_no as order_no
 from enriched_order_offline_transactions),
enriched_order_offline_transactions_enriched_order_online_transactions_agg_cte_attributor as (select
retail_unification_id, season,
count(CASE WHEN season is not null THEN order_no ELSE NULL END) AS preferred_season_cnt
 from
enriched_order_offline_transactions_enriched_order_online_transactions_cte_attributor
group by retail_unification_id, season)
select * from enriched_order_offline_transactions_enriched_order_online_transactions_agg_cte_attributor;