id: null
name: Retail Starter Pack
description: Retail Starter Pack
scheduleType: none
scheduleOption: ""
timezone: UTC
matrixUpdatedAt: ""
workflowHiveOnly: false
hiveEngineVersion: cdpaudience
hivePoolName: ""
prestoPoolName: ""
population:
maxActivationBehaviorRow: 20
allowActivationBehavior: false
rootFolderId: ""
master:
  parentDatabaseName: gld_retail
  parentTableName: parent_table
attributes:
- audience: null
  id: null
  name: Age
  type: number
  parentDatabaseName: gld_retail
  parentTableName: enriched_customers
  parentColumn: trfmd_age
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: trfmd_age
  groupingName: Demographics
- audience: null
  id: null
  name: Name
  type: string
  parentDatabaseName: gld_retail
  parentTableName: enriched_customers
  parentColumn: trfmd_full_name
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: trfmd_full_name
  groupingName: Identity
- audience: null
  id: null
  name: Gender Code
  type: string
  parentDatabaseName: gld_retail
  parentTableName: enriched_customers
  parentColumn: trfmd_gender
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: trfmd_gender
  groupingName: Demographics
- audience: null
  id: null
  name: Country
  type: string
  parentDatabaseName: gld_retail
  parentTableName: enriched_customers
  parentColumn: country
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: country
  groupingName: Geo
- audience: null
  id: null
  name: Loyalty Status
  type: number
  parentDatabaseName: gld_retail
  parentTableName: enriched_customers
  parentColumn: loyalty_status
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: loyalty_status
  groupingName: Loyalty
- audience: null
  id: null
  name: Email
  type: string
  parentDatabaseName: gld_retail
  parentTableName: parent_table
  parentColumn: email
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: email
  groupingName: Identity
- audience: null
  id: null
  name: Phone Number
  type: string
  parentDatabaseName: gld_retail
  parentTableName: parent_table
  parentColumn: phone_number
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: phone_number
  groupingName: Identity
- audience: null
  id: null
  name: Average Order Value
  type: number
  parentDatabaseName: gld_retail
  parentTableName: derived_attributes
  parentColumn: aov
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: aov
  groupingName: Purchase
- audience: null
  id: null
  name: Last Purchase Date
  type: number
  parentDatabaseName: gld_retail
  parentTableName: derived_attributes
  parentColumn: last_purchase_date
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: last_purchase_date
  groupingName: Purchase
- audience: null
  id: null
  name: Web Visits Last 7days
  type: number
  parentDatabaseName: gld_retail
  parentTableName: derived_attributes
  parentColumn: web_visits_last_7days
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: web_visits_last_7days
  groupingName: Engagement
- audience: null
  id: null
  name: Purchase Last 30days
  type: number
  parentDatabaseName: gld_retail
  parentTableName: derived_attributes
  parentColumn: purchases_last_30days
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: purchases_last_30days
  groupingName: Purchase
- audience: null
  id: null
  name: Lifetime Value
  type: number
  parentDatabaseName: gld_retail
  parentTableName: derived_attributes
  parentColumn: ltv
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: ltv
  groupingName: Purchase
- audience: null
  id: null
  name: Last Store Visit
  type: number
  parentDatabaseName: gld_retail
  parentTableName: derived_attributes
  parentColumn: last_store_visit
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: last_store_visit
  groupingName: Engagement
- audience: null
  id: null
  name: Last Email Date
  type: number
  parentDatabaseName: gld_retail
  parentTableName: derived_attributes
  parentColumn: last_email_date
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: last_email_date
  groupingName: Engagement
- audience: null
  id: null
  name: Email Hardbounce
  type: number
  parentDatabaseName: gld_retail
  parentTableName: derived_attributes
  parentColumn: email_hardbounce
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: email_hardbounce
  groupingName: Engagement
- audience: null
  id: null
  name: Email SoftBounce Greater Than 5
  type: string
  parentDatabaseName: gld_retail
  parentTableName: derived_attributes
  parentColumn: email_softbounce_gt5
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: email_softbounce_gt5
  groupingName: Engagement
- audience: null
  id: null
  name: Preffered Season
  type: string
  parentDatabaseName: gld_retail
  parentTableName: derived_attributes
  parentColumn: preferred_season
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixColumnName: preferred_season
  groupingName: Engagement
behaviors:
- audience: null
  id: null
  name: Email Activity
  parentDatabaseName: gld_retail
  parentTableName: enriched_email_activity
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixDatabaseName: cdp_audience_670285
  matrixTableName: behavior_enriched_email_activity
  allColumns: false
  defaultTimeFilterEnabled: false
  isRealtime: false
  schema:
  - name: Activity Type
    type: string
    parentColumn: trfmd_activity_type
    matrixColumnName: trfmd_activity_type
  - name: Campaign Name
    type: string
    parentColumn: trfmd_campaign_name
    matrixColumnName: trfmd_campaign_name
- audience: null
  id: null
  name: Online Transactions
  parentDatabaseName: gld_retail
  parentTableName: enriched_order_online_transactions
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixDatabaseName: cdp_audience_670285
  matrixTableName: behavior_enriched_order_online_transactions
  allColumns: false
  defaultTimeFilterEnabled: false
  isRealtime: false
  schema:
  - name: Order Type
    type: string
    parentColumn: trfmd_order_type
    matrixColumnName: trfmd_order_type
  - name: Payment Method
    type: string
    parentColumn: trfmd_payment_method
    matrixColumnName: trfmd_payment_method
  - name: Season
    type: string
    parentColumn: trfmd_season
    matrixColumnName: trfmd_season
  - name: Promo
    type: number
    parentColumn: promo_flag
    matrixColumnName: promo_flag
  - name: Markdown
    type: number
    parentColumn: markdown_flag
    matrixColumnName: markdown_flag
  - name: Guest Checkout
    type: number
    parentColumn: guest_checkout_flag
    matrixColumnName: guest_checkout_flag
  - name: Amount
    type: number
    parentColumn: amount
    matrixColumnName: amount
  - name: Order Date
    type: number
    parentColumn: order_datetime
    matrixColumnName: order_datetime
  - name: Projected Delivery Date
    type: number
    parentColumn: projected_delivery_date
    matrixColumnName: projected_delivery_date
- audience: null
  id: null
  name: Offline Transactions
  parentDatabaseName: gld_retail
  parentTableName: enriched_order_offline_transactions
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixDatabaseName: cdp_audience_670285
  matrixTableName: behavior_enriched_order_offline_transactions
  allColumns: false
  defaultTimeFilterEnabled: false
  isRealtime: false
  schema:
  - name: Amount
    type: number
    parentColumn: amount
    matrixColumnName: amount
  - name: trfmd_payment_method
    type: string
    parentColumn: trfmd_payment_method
    matrixColumnName: trfmd_payment_method
  - name: Order Date
    type: number
    parentColumn: order_datetime
    matrixColumnName: order_datetime
  - name: Season
    type: string
    parentColumn: trfmd_season
    matrixColumnName: trfmd_season
  - name: Store Address
    type: string
    parentColumn: trfmd_store_address
    matrixColumnName: trfmd_store_address
  - name: Store City
    type: string
    parentColumn: trfmd_store_city
    matrixColumnName: trfmd_store_city
  - name: Store Country
    type: string
    parentColumn: trfmd_store_country
    matrixColumnName: trfmd_store_country
  - name: Store Postalcode
    type: string
    parentColumn: trfmd_store_postal_code
    matrixColumnName: trfmd_store_postal_code
  - name: Store State
    type: string
    parentColumn: trfmd_store_state
    matrixColumnName: trfmd_store_state
- audience: null
  id: null
  name: All Transaction Details
  parentDatabaseName: gld_retail
  parentTableName: enriched_order_details
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixDatabaseName: cdp_audience_670285
  matrixTableName: behavior_enriched_order_details
  allColumns: false
  defaultTimeFilterEnabled: false
  isRealtime: false
  schema:
  - name: Discount
    type: number
    parentColumn: discount_offered
    matrixColumnName: discount_offered
  - name: Order Transaction Type
    type: string
    parentColumn: trfmd_order_transaction_type
    matrixColumnName: trfmd_order_transaction_type
  - name: Product Color
    type: string
    parentColumn: trfmd_product_color
    matrixColumnName: trfmd_product_color
  - name: Product Department
    type: string
    parentColumn: trfmd_product_department
    matrixColumnName: trfmd_product_department
  - name: Product Description
    type: string
    parentColumn: trfmd_product_description
    matrixColumnName: trfmd_product_description
  - name: Product Name
    type: string
    parentColumn: trfmd_product_name
    matrixColumnName: trfmd_product_name
  - name: Product Size
    type: string
    parentColumn: trfmd_product_size
    matrixColumnName: trfmd_product_size
  - name: Product Sub Department
    type: string
    parentColumn: trfmd_product_sub_department
    matrixColumnName: trfmd_product_sub_department
  - name: List Price
    type: number
    parentColumn: list_price
    matrixColumnName: list_price
  - name: Net Price
    type: number
    parentColumn: net_price
    matrixColumnName: net_price
- audience: null
  id: null
  name: Pageviews
  parentDatabaseName: gld_retail
  parentTableName: enriched_pageviews
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixDatabaseName: cdp_audience_670285
  matrixTableName: behavior_enriched_pageviews
  allColumns: false
  defaultTimeFilterEnabled: false
  isRealtime: false
  schema:
  - name: Browser
    type: string
    parentColumn: td_browser
    matrixColumnName: td_browser
  - name: Browser Version
    type: string
    parentColumn: td_browser_version
    matrixColumnName: td_browser_version
  - name: Charset
    type: string
    parentColumn: td_charset
    matrixColumnName: td_charset
  - name: Color
    type: string
    parentColumn: td_color
    matrixColumnName: td_color
  - name: Description
    type: string
    parentColumn: td_description
    matrixColumnName: td_description
  - name: Host
    type: string
    parentColumn: td_host
    matrixColumnName: td_host
  - name: Language
    type: string
    parentColumn: td_language
    matrixColumnName: td_language
  - name: OS
    type: string
    parentColumn: td_os
    matrixColumnName: td_os
  - name: Path
    type: string
    parentColumn: td_path
    matrixColumnName: td_path
  - name: Platform
    type: string
    parentColumn: td_platform
    matrixColumnName: td_platform
  - name: Referrer
    type: string
    parentColumn: td_referrer
    matrixColumnName: td_referrer
  - name: Screen
    type: string
    parentColumn: td_screen
    matrixColumnName: td_screen
  - name: Title
    type: string
    parentColumn: td_title
    matrixColumnName: td_title
  - name: URL
    type: string
    parentColumn: td_url
    matrixColumnName: td_url
  - name: User Agent
    type: string
    parentColumn: td_user_agent
    matrixColumnName: td_user_agent
- audience: null
  id: null
  name: Consent
  parentDatabaseName: gld_retail
  parentTableName: enriched_consents
  parentKey: retail_unification_id
  foreignKey: retail_unification_id
  matrixDatabaseName: cdp_audience_670285
  matrixTableName: behavior_enriched_consents
  allColumns: false
  defaultTimeFilterEnabled: false
  isRealtime: false
  schema:
  - name: Consent Flag
    type: number
    parentColumn: consent_flag
    matrixColumnName: consent_flag
  - name: Consent Type
    type: string
    parentColumn: trfmd_consent_type
    matrixColumnName: trfmd_consent_type